openy_rose_image_fields:
  footer_logo: openy_rose_footer_logo
  camp_section_logo: openy_rose_camp_section_logo
  camp_footer_logo: openy_rose_camp_footer_logo
  camp_favicon: openy_rose_camp_favicon
css_enabled: 1
css: ''
plaintext_enabled: 0
autopreview_enabled: 0
preview_path: ''
_core:
  default_config_hash: 9eL0MANEzSmZrtfc-H9U23rpKSt88OsZNFz27rcbBr4
