cookie_lifetime: 28800
header_replacements:
  -
    block_id: 'Disable Mobile Section Lead Copy'
    selector: '.page-middle .lead-copy'
footer_replacements:
  -
    block_id: 'Disable Footer'
    selector: '#page-footer'
_core:
  default_config_hash: YqYOK8Zs4ltNYwu0uxfm-916J1qujr1MxH6qO_dVDBg
